/* =============================================================================
 * GOTHAM HOP — CORE RULES LAYER  (config.js)
 * -----------------------------------------------------------------------------
 * This file is part of the GOVERNED CORE. It defines the global rules of the
 * game and the catalog of building blocks that community street layouts are
 * allowed to reference.
 *
 *   • Editing this file changes the game for EVERY street.
 *   • Changes here should go through the limited set of core maintainers
 *     (see CODEOWNERS / docs/GOVERNANCE.md).
 *
 * Street authors do NOT edit this file. They compose layouts in /streets/*.json
 * using only the sprites and lane types declared here.
 * ===========================================================================*/

window.GOTHAM = window.GOTHAM || {};

GOTHAM.RULES = {
  // --- Grid -----------------------------------------------------------------
  COLS: 13,            // logical columns; every street is this wide
  TILE: 48,           // pixel size of one tile (rendering scales from this)

  // --- Scoring --------------------------------------------------------------
  SCORE_FORWARD: 10,        // points for each new furthest row reached
  SCORE_GOAL: 200,          // points for parking the hopper in a goal slot
  SCORE_STREET_CLEAR: 1000,  // bonus for filling every goal slot on a street
  SCORE_TIME_BONUS: 10,     // points per whole second left when reaching a goal

  // --- Difficulty curve -----------------------------------------------------
  // Every cleared street nudges hazard speed up, so community streets stay fair
  // early and get spicier deep into a run. Kept gentle so the game is welcoming.
  SPEED_RAMP_PER_STREET: 0.06,
  MAX_SPEED_MULTIPLIER: 1.6,

  // --- Feel -----------------------------------------------------------------
  HOP_MS: 95,               // how long the hop animation takes (snappy)
  RESPAWN_GRACE: 1.2,       // seconds of invulnerability after a respawn
  DEFAULT_AVATAR: '🐸',     // homage to the original; streets may override
};

/* -----------------------------------------------------------------------------
 * DIFFICULTY PRESETS
 * A single global knob the player picks before a run. It scales hazard speed,
 * the clock, and the number of lives, and decides whether reaching the goal
 * row forgivingly snaps to the nearest open stoop. Streets are authored once;
 * these presets make any street accessible or punishing without re-authoring.
 * ---------------------------------------------------------------------------*/
GOTHAM.DIFFICULTY = {
  //                speed multiplier  lives  clock   snap   per-street ramp
  easy:   { label: 'Easy',   speed: 0.40, lives: 8,  time: 90, snapGoal: true,  ramp: 0.02 },
  normal: { label: 'Normal', speed: 0.75, lives: 5,  time: 55, snapGoal: true,  ramp: 0.05 },
  hard:   { label: 'Hard',   speed: 1.20, lives: 3,  time: 35, snapGoal: false, ramp: 0.09 },
};
GOTHAM.DEFAULT_DIFFICULTY = 'easy';

/* -----------------------------------------------------------------------------
 * SPRITE CATALOG
 * The whitelist of things a street is allowed to put in a lane. Each entry
 * fixes the length (in tiles) and look so that gameplay is consistent and
 * balanced no matter who authored the street.
 *
 *   kind: 'vehicle' lives on ROAD lanes and is lethal on contact.
 *   kind: 'platform' lives on WATER lanes and is the only safe footing.
 * ---------------------------------------------------------------------------*/
GOTHAM.CATALOG = {
  // Road hazards ------------------------------------------------------------
  // `shape` selects the vector drawing routine in sprites.js; `color` is its
  // base paint. No emoji — everything on the board is drawn.
  taxi:   { kind: 'vehicle', len: 1, shape: 'car',    color: '#f7c948' },
  car:    { kind: 'vehicle', len: 1, shape: 'car',    color: '#3b82f6' },
  police: { kind: 'vehicle', len: 1, shape: 'police', color: '#1d4ed8' },
  bike:   { kind: 'vehicle', len: 1, shape: 'bike',   color: '#22d3ee' },
  bus:    { kind: 'vehicle', len: 2, shape: 'bus',    color: '#60a5fa' },
  truck:  { kind: 'vehicle', len: 2, shape: 'truck',  color: '#e2e8f0' },
  cart:   { kind: 'vehicle', len: 1, shape: 'cart',   color: '#fb923c' }, // halal/food cart
  wallet: { kind: 'vehicle', len: 1, shape: 'wallet', color: '#92400e' }, // pickpocket loot
  purse:  { kind: 'vehicle', len: 1, shape: 'purse',  color: '#be123c' },

  // Water footing -----------------------------------------------------------
  ferry:  { kind: 'platform', len: 3, shape: 'ferry', color: '#f97316' },
  barge:  { kind: 'platform', len: 2, shape: 'barge', color: '#64748b' },
  raft:   { kind: 'platform', len: 2, shape: 'raft',  color: '#92400e' },
  kayak:  { kind: 'platform', len: 1, shape: 'kayak', color: '#eab308' },
};

/* -----------------------------------------------------------------------------
 * LANE TYPES — the vocabulary streets build from.
 * ---------------------------------------------------------------------------*/
GOTHAM.LANE_TYPES = {
  start: 'Sidewalk where the hopper begins each life. Always safe.',
  safe:  'A median / sidewalk. Safe to stand on.',
  road:  'Traffic flows across; touching a vehicle is fatal.',
  water: 'The Hudson; you must ride a platform or you fall in.',
  goal:  'Destination stoops; reach an empty slot to bank it.',
};
